"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from artemis_cam.proto import signaling_pb2 as _signaling_pb2
from collections import abc as _abc
from grpc import aio as _aio
import abc as _abc_1
import grpc as _grpc
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import Self as _Self
else:
    from typing_extensions import Self as _Self

_T = _typing.TypeVar("_T")

class _MaybeAsyncIterator(_abc.AsyncIterator[_T], _abc.Iterator[_T], metaclass=_abc_1.ABCMeta): ...

class _ServicerContext(_grpc.ServicerContext, _aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str

class SignalingServiceStub:
    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> SignalingServiceAsyncStub: ...
    Signal: _grpc.StreamStreamMultiCallable[_signaling_pb2.SignalMessage, _signaling_pb2.SignalMessage]

@_typing.type_check_only
class SignalingServiceAsyncStub(SignalingServiceStub):
    def __init__(self, channel: _aio.Channel) -> None: ...
    Signal: _aio.StreamStreamMultiCallable[_signaling_pb2.SignalMessage, _signaling_pb2.SignalMessage]  # type: ignore[assignment]

class SignalingServiceServicer(metaclass=_abc_1.ABCMeta):
    @_abc_1.abstractmethod
    def Signal(
        self,
        request_iterator: _MaybeAsyncIterator[_signaling_pb2.SignalMessage],
        context: _ServicerContext,
    ) -> _typing.Union[_abc.Iterator[_signaling_pb2.SignalMessage], _abc.AsyncIterator[_signaling_pb2.SignalMessage]]: ...

def add_SignalingServiceServicer_to_server(servicer: SignalingServiceServicer, server: _typing.Union[_grpc.Server, _aio.Server]) -> None: ...
