"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class SessionDescription(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TYPE_FIELD_NUMBER: _builtins.int
    SDP_FIELD_NUMBER: _builtins.int
    type: _builtins.str
    sdp: _builtins.str
    def __init__(
        self,
        *,
        type: _builtins.str = ...,
        sdp: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["sdp", b"sdp", "type", b"type"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___SessionDescription: _TypeAlias = SessionDescription  # noqa: Y015

@_typing.final
class IceCandidate(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    FOUNDATION_FIELD_NUMBER: _builtins.int
    COMPONENT_FIELD_NUMBER: _builtins.int
    PROTOCOL_FIELD_NUMBER: _builtins.int
    PRIORITY_FIELD_NUMBER: _builtins.int
    IP_FIELD_NUMBER: _builtins.int
    PORT_FIELD_NUMBER: _builtins.int
    TYPE_FIELD_NUMBER: _builtins.int
    RELATED_ADDRESS_FIELD_NUMBER: _builtins.int
    RELATED_PORT_FIELD_NUMBER: _builtins.int
    SDP_MID_FIELD_NUMBER: _builtins.int
    SDP_MLINE_INDEX_FIELD_NUMBER: _builtins.int
    TCP_TYPE_FIELD_NUMBER: _builtins.int
    foundation: _builtins.str
    component: _builtins.int
    protocol: _builtins.str
    priority: _builtins.int
    ip: _builtins.str
    port: _builtins.int
    type: _builtins.str
    related_address: _builtins.str
    related_port: _builtins.int
    sdp_mid: _builtins.str
    sdp_mline_index: _builtins.int
    tcp_type: _builtins.str
    def __init__(
        self,
        *,
        foundation: _builtins.str = ...,
        component: _builtins.int = ...,
        protocol: _builtins.str = ...,
        priority: _builtins.int = ...,
        ip: _builtins.str = ...,
        port: _builtins.int = ...,
        type: _builtins.str = ...,
        related_address: _builtins.str = ...,
        related_port: _builtins.int = ...,
        sdp_mid: _builtins.str = ...,
        sdp_mline_index: _builtins.int = ...,
        tcp_type: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["component", b"component", "foundation", b"foundation", "ip", b"ip", "port", b"port", "priority", b"priority", "protocol", b"protocol", "related_address", b"related_address", "related_port", b"related_port", "sdp_mid", b"sdp_mid", "sdp_mline_index", b"sdp_mline_index", "tcp_type", b"tcp_type", "type", b"type"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___IceCandidate: _TypeAlias = IceCandidate  # noqa: Y015

@_typing.final
class SignalMessage(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    OFFER_FIELD_NUMBER: _builtins.int
    ANSWER_FIELD_NUMBER: _builtins.int
    CANDIDATE_FIELD_NUMBER: _builtins.int
    END_OF_CANDIDATES_FIELD_NUMBER: _builtins.int
    CLOSE_FIELD_NUMBER: _builtins.int
    end_of_candidates: _builtins.bool
    @_builtins.property
    def offer(self) -> Global___SessionDescription: ...
    @_builtins.property
    def answer(self) -> Global___SessionDescription: ...
    @_builtins.property
    def candidate(self) -> Global___IceCandidate: ...
    @_builtins.property
    def close(self) -> Global___CloseSessionRequest: ...
    def __init__(
        self,
        *,
        offer: Global___SessionDescription | None = ...,
        answer: Global___SessionDescription | None = ...,
        candidate: Global___IceCandidate | None = ...,
        end_of_candidates: _builtins.bool = ...,
        close: Global___CloseSessionRequest | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["answer", b"answer", "candidate", b"candidate", "close", b"close", "end_of_candidates", b"end_of_candidates", "offer", b"offer", "payload", b"payload"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["answer", b"answer", "candidate", b"candidate", "close", b"close", "end_of_candidates", b"end_of_candidates", "offer", b"offer", "payload", b"payload"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_payload: _TypeAlias = _typing.Literal["offer", "answer", "candidate", "end_of_candidates", "close"]  # noqa: Y015
    _WhichOneofArgType_payload: _TypeAlias = _typing.Literal["payload", b"payload"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_payload) -> _WhichOneofReturnType_payload | None: ...

Global___SignalMessage: _TypeAlias = SignalMessage  # noqa: Y015

@_typing.final
class CloseSessionRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___CloseSessionRequest: _TypeAlias = CloseSessionRequest  # noqa: Y015
