syntax = "proto3";

package artemis_cam.signaling.v1;

service SignalingService {
  rpc Signal(stream SignalMessage) returns (stream SignalMessage);
}

message SessionDescription {
  string type = 1;
  string sdp = 2;
}

message IceCandidate {
  string foundation = 1;
  uint32 component = 2;
  string protocol = 3;
  uint64 priority = 4;
  string ip = 5;
  uint32 port = 6;
  string type = 7;
  string related_address = 8;
  uint32 related_port = 9;
  string sdp_mid = 10;
  uint32 sdp_mline_index = 11;
  string tcp_type = 12;
}

message SignalMessage {
  oneof payload {
    SessionDescription offer = 1;
    SessionDescription answer = 2;
    IceCandidate candidate = 3;
    bool end_of_candidates = 4;
    CloseSessionRequest close = 5;
  }
}

message CloseSessionRequest {}
