# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: artemis_cam/proto/signaling.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'artemis_cam/proto/signaling.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!artemis_cam/proto/signaling.proto\x12\x18\x61rtemis_cam.signaling.v1\"/\n\x12SessionDescription\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x0b\n\x03sdp\x18\x02 \x01(\t\"\xec\x01\n\x0cIceCandidate\x12\x12\n\nfoundation\x18\x01 \x01(\t\x12\x11\n\tcomponent\x18\x02 \x01(\r\x12\x10\n\x08protocol\x18\x03 \x01(\t\x12\x10\n\x08priority\x18\x04 \x01(\x04\x12\n\n\x02ip\x18\x05 \x01(\t\x12\x0c\n\x04port\x18\x06 \x01(\r\x12\x0c\n\x04type\x18\x07 \x01(\t\x12\x17\n\x0frelated_address\x18\x08 \x01(\t\x12\x14\n\x0crelated_port\x18\t \x01(\r\x12\x0f\n\x07sdp_mid\x18\n \x01(\t\x12\x17\n\x0fsdp_mline_index\x18\x0b \x01(\r\x12\x10\n\x08tcp_type\x18\x0c \x01(\t\"\xb3\x02\n\rSignalMessage\x12=\n\x05offer\x18\x01 \x01(\x0b\x32,.artemis_cam.signaling.v1.SessionDescriptionH\x00\x12>\n\x06\x61nswer\x18\x02 \x01(\x0b\x32,.artemis_cam.signaling.v1.SessionDescriptionH\x00\x12;\n\tcandidate\x18\x03 \x01(\x0b\x32&.artemis_cam.signaling.v1.IceCandidateH\x00\x12\x1b\n\x11\x65nd_of_candidates\x18\x04 \x01(\x08H\x00\x12>\n\x05\x63lose\x18\x05 \x01(\x0b\x32-.artemis_cam.signaling.v1.CloseSessionRequestH\x00\x42\t\n\x07payload\"\x15\n\x13\x43loseSessionRequest2r\n\x10SignalingService\x12^\n\x06Signal\x12\'.artemis_cam.signaling.v1.SignalMessage\x1a\'.artemis_cam.signaling.v1.SignalMessage(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'artemis_cam.proto.signaling_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SESSIONDESCRIPTION']._serialized_start=63
  _globals['_SESSIONDESCRIPTION']._serialized_end=110
  _globals['_ICECANDIDATE']._serialized_start=113
  _globals['_ICECANDIDATE']._serialized_end=349
  _globals['_SIGNALMESSAGE']._serialized_start=352
  _globals['_SIGNALMESSAGE']._serialized_end=659
  _globals['_CLOSESESSIONREQUEST']._serialized_start=661
  _globals['_CLOSESESSIONREQUEST']._serialized_end=682
  _globals['_SIGNALINGSERVICE']._serialized_start=684
  _globals['_SIGNALINGSERVICE']._serialized_end=798
# @@protoc_insertion_point(module_scope)
